### ISSUE TITLE
A query for dataset source

### ISSUE THREAD

**Issue by hanquansanren** [gwxie/Synthesize-Distorted-Image-and-Its-Control-Points#3]
Hi Guowang,
Thanks for your excellent work on Document Dewarping with Control Points. I try to synthesize a unified warped document dataset by myself. This dataset will merge Doc3D, Doc in wild, and your work. But I cannot get access to the original flattened images in the paper 
 of Document Dewarping with Control Points.
So, can you share some information about the source of the original flattened image? such as the scanned dataset source

Best wishes,
Weiguang Zhang

**Comment by hanquansanren** [comment]
Including the background dataset, can you tell me more about the original dataset source? 
Many thanks for your response.

**Comment by gwxie** [comment]
> Including the background dataset, can you tell me more about the original dataset source? Many thanks for your response.

Hi Weiguang,
Most of this batch of data comes from the Internet and research groups. I have graduated, and the most original data cannot be uploaded. You can use control points to rectify each image once, the resolution may be lower, but most should be flat like the original.

**Comment by hanquansanren** [comment]
Hello Guowang,
Thanks for your feedback, I will check further on the Internet and group.
